@baseUrl=http://localhost:4000/api

### PRODUCT ALL
GET {{baseUrl}}/products
Accept: application/json
Content-Type: application/json


### PRODUCT ID
GET {{baseUrl}}/products/a
Accept: application/json
Content-Type: application/json


### ORDER CREATE
POST {{baseUrl}}/order
Accept: application/json
Content-Type: application/json

{
    "quantity": 5,
    "customerName": "Rocky Triady",
    "productId": "a"
}

### ORDER ALL
GET {{baseUrl}}/order
Accept: application/json
Content-Type: application/json


### ORDER ID
GET {{baseUrl}}/order/1
Accept: application/json
Content-Type: application/json